#!/usr/bin/env python3
"""Generate deterministic wheel-only SHA-256 locks from exact PyPI pins."""

from __future__ import annotations

import argparse
from functools import lru_cache
import json
import os
import re
import tempfile
import urllib.parse
import urllib.request
from collections import OrderedDict
from pathlib import Path
from typing import Iterable, MutableMapping, Optional, Sequence, Tuple


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_LOCKS = (
    (Path("requirements-project.txt"), Path("requirements-project.lock")),
    (Path("requirements-python38.txt"), Path("requirements-python38.lock")),
    (Path("requirements-benchmark.txt"), Path("requirements-benchmark.lock")),
)
PIN = re.compile(r"^([A-Za-z0-9][A-Za-z0-9._-]*)==([^\s;]+)$")
LOCK_PIN = re.compile(r"^([A-Za-z0-9][A-Za-z0-9._-]*)==([^\s;]+) \\$")
LOCK_HASH = re.compile(r"^--hash=sha256:([0-9a-f]{64})(?: \\)?$")


def _pins(
    path: Path,
    collected: MutableMapping[str, Tuple[str, str]],
    project_root: Path,
    active: Tuple[Path, ...] = (),
) -> None:
    project_root = project_root.resolve()
    lexical_path = Path(os.path.abspath(str(path)))
    try:
        relative = lexical_path.relative_to(project_root)
    except ValueError as exc:
        raise ValueError("requirements input escapes project root: %s" % path) from exc
    component = project_root
    for part in relative.parts:
        component = component / part
        if component.is_symlink():
            raise ValueError("requirements input contains a symlink: %s" % path)
    path = lexical_path.resolve()
    try:
        path.relative_to(project_root)
    except ValueError as exc:
        raise ValueError("requirements input resolves outside project root: %s" % path) from exc
    if path in active:
        raise ValueError("recursive requirements include: %s" % path)
    for line_number, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("-r ") or line.startswith("--requirement "):
            include = line.split(maxsplit=1)[1]
            _pins(
                path.parent / include,
                collected,
                project_root,
                active + (path,),
            )
            continue
        match = PIN.fullmatch(line)
        if match is None:
            raise ValueError("%s:%d is not an exact unmarked pin" % (path, line_number))
        display_name, version = match.groups()
        key = re.sub(r"[-_.]+", "-", display_name).lower()
        prior = collected.get(key)
        if prior is not None and prior[1] != version:
            raise ValueError(
                "conflicting pins for %s: %s and %s" % (display_name, prior[1], version)
            )
        if prior is None:
            collected[key] = (display_name, version)


@lru_cache(maxsize=None)
def _wheel_hashes(name: str, version: str) -> Sequence[str]:
    project = urllib.parse.quote(name, safe="")
    release = urllib.parse.quote(version, safe="")
    request = urllib.request.Request(
        "https://pypi.org/pypi/%s/%s/json" % (project, release),
        headers={"User-Agent": "carma-lock-generator/1"},
    )
    with urllib.request.urlopen(request, timeout=30) as response:
        payload = json.load(response)
    hashes = sorted(
        {
            item["digests"]["sha256"]
            for item in payload.get("urls", ())
            if item.get("packagetype") == "bdist_wheel"
            and not item.get("yanked", False)
            and item.get("digests", {}).get("sha256")
        }
    )
    if not hashes:
        raise ValueError("%s==%s has no non-yanked wheel on PyPI" % (name, version))
    return hashes


def _render(source: Path, pins: Iterable[Tuple[str, str]]) -> str:
    lines = [
        "# Generated by scripts/generate_hashed_locks.py; do not edit by hand.",
        "# Source pins: %s" % source.name,
        "# Contains SHA-256 hashes for every non-yanked wheel published for each pin.",
        "",
    ]
    for name, version in pins:
        hashes = _wheel_hashes(name, version)
        lines.append("%s==%s \\" % (name, version))
        for index, digest in enumerate(hashes):
            suffix = " \\" if index + 1 < len(hashes) else ""
            lines.append("    --hash=sha256:%s%s" % (digest, suffix))
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _locked_pins(path: Path) -> "OrderedDict[str, Tuple[str, str]]":
    locked: "OrderedDict[str, Tuple[str, str]]" = OrderedDict()
    current_key: Optional[str] = None
    current_hashes = []

    def finish_entry() -> None:
        if current_key is None:
            return
        if not current_hashes:
            raise ValueError("%s has an unhashed pin for %s" % (path, current_key))
        if current_hashes != sorted(set(current_hashes)):
            raise ValueError("%s has duplicate or unsorted hashes for %s" % (path, current_key))

    for line_number, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        pin = LOCK_PIN.fullmatch(line)
        if pin is not None:
            finish_entry()
            name, version = pin.groups()
            current_key = re.sub(r"[-_.]+", "-", name).lower()
            if current_key in locked:
                raise ValueError("%s:%d duplicates %s" % (path, line_number, name))
            locked[current_key] = (name, version)
            current_hashes = []
            continue
        digest = LOCK_HASH.fullmatch(line)
        if digest is not None and current_key is not None:
            current_hashes.append(digest.group(1))
            continue
        raise ValueError("%s:%d is not a generated lock line" % (path, line_number))
    finish_entry()
    return locked


def check(source: Path, destination: Path, project_root: Path) -> None:
    expected: "OrderedDict[str, Tuple[str, str]]" = OrderedDict()
    _pins(source, expected, project_root)
    observed = _locked_pins(destination)
    if list(observed.items()) != list(expected.items()):
        raise ValueError("%s does not match exact pins from %s" % (destination, source))


def generate(source: Path, destination: Path, project_root: Path) -> None:
    collected: "OrderedDict[str, Tuple[str, str]]" = OrderedDict()
    _pins(source, collected, project_root)
    rendered = _render(source, collected.values())
    destination.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        mode="w",
        encoding="utf-8",
        dir=str(destination.parent),
        prefix=destination.name + ".",
        delete=False,
    ) as temporary:
        temporary.write(rendered)
        temporary_path = Path(temporary.name)
    temporary_path.replace(destination)
    destination.chmod(0o644)


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--project-root",
        type=Path,
        default=PROJECT_ROOT,
        help="repository root containing the requirement inputs",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="validate existing locks against their pin inputs without network access",
    )
    args = parser.parse_args(argv)
    root = args.project_root.resolve()
    for source, destination in DEFAULT_LOCKS:
        if args.check:
            check(root / source, root / destination, root)
        else:
            generate(root / source, root / destination, root)
        print(destination.as_posix())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
